name: r

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
      -
        name: List keys
        run: gpg -K

      - name: Build site and deploy maven registry
        env:
          GPG_KEYNAME: ${{ secrets.PGP_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          OSSRH_PWD_TOKEN: ${{ secrets.OSSRH_PWD_TOKEN }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
        run: mvn -V -B --no-transfer-progress --settings .github/maven-settings.xml -P release clean deploy
