# https://docs.github.com/en/github-ae@latest/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [master, jdk8-version]
  pull_request:
    branches: [master, jdk8-version]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "zulu"

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Report Junit
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test results
          path: "**/**/surefire-reports/*.xml"
          reporter: java-junit
          fail-on-error: true

      - name: Run PMD
        run: mvn pmd:check

      - name: Report PMD
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: "target/pmd.xml"
          title: PMD Result

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "zulu"

      - name: Build and deploy maven registry
        env:
          GPG_KEYNAME: ${{ secrets.PGP_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          OSSRH_PWD_TOKEN: ${{ secrets.OSSRH_PWD_TOKEN }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
        run: mvn -V -B -DskipTests=true --no-transfer-progress --settings .github/maven-settings.xml -P release deploy
