name: RELEASE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PPG_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
      - name: Checkout code
        uses: actions/checkout@master # don't get confused by @master - it is the version of the checkout action. You repo will be checked out with ${{ github.ref }}
      - name: Build site and deploy maven registry
        env:
          GPG_KEYNAME: ${{ secrets.PGP_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          OSSRH_PWD_TOKEN: ${{ secrets.OSSRH_PWD_TOKEN }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
        run: mvn -V -B --no-transfer-progress --settings .github/maven-settings.xml -P release clean deploy
